name: Build Release Versions

on:
  push:
    branches:
      - master

jobs:
  build_go:
    strategy:
      matrix:
        architecture: [ "amd64", "arm64" ]
        os: [ "linux", "darwin" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Install dependencies
        run: go get

      - name: Build
        env:
          OS: ${{ matrix.os }}
          ARCH: ${{ matrix.architecture }}
        run: env GOOS=$OS GOARCH=$ARCH go build -o "versionizer-$OS-$ARCH"

      - uses: actions/upload-artifact@master
        with:
          name: versionizer-${{ matrix.os }}-${{ matrix.architecture }}
          path: versionizer-${{ matrix.os }}-${{ matrix.architecture }}
